### ISSUE TITLE
Issues installing robflow-cli via npm on Pop_OS

### ISSUE THREAD

**Issue by elmonkey** [roboflow-ai/roboflow-cli#17]
Error when installing via npm (also why npm? -- doesn't matter here is the issue)

## INSTALLING NPM & ROBOBLOF-CLI

* `sudo apt install npm`
*  `npm i -g roboflow-cli` --> doesnt work, requires `sudo`
* `sudo npm i -g roboflow-cli` --> produces the following:

```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'yaml@2.3.0',
npm WARN EBADENGINE   required: { node: '>= 14', npm: '>= 7' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.

changed 198 packages, and audited 394 packages in 7s

48 packages are looking for funding
  run `npm fund` for details

4 high severity vulnerabilities

To address issues that do not require attention, run:
  npm audit fix

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
```

* running npm audit or npm audit fix doesnt solve the issue(s)

---
`roboflow -h ` produces:
```
/usr/local/lib/node_modules/roboflow-cli/cli/core.js:98
    const projects = workspaceData.workspace?.projects;
                                             ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/roboflow-cli/cli/commands/workspace.js:6:52)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
```
---
## SYSTEM:
System: pop.os 22.04  <-- this might be the culprit
`npm --version` --> 8.5.1
Disclaimer: never used npm before

**Comment by yeldarby** [comment]
```
npm WARN EBADENGINE   required: { node: '>= 14', npm: '>= 7' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
```
This is saying you're on node 12 but need at least node 14.

[Node 12 was EOL 2.5 years ago](https://endoflife.date/nodejs) with security support ended over a year ago now. Current LTS version is Node 18 (will transition to Node 20 soon)
